locale: "en-US"
site_theme: "default"
title: "Jimin Lee"
title_separator: "-"
name: &name "Jimin Lee"
description: "수정_Your Name's academic portfolio"
url: https://jiminlee-research.github.io
baseurl: ""
repository: "jiminlee-research.github.io"

author:
  avatar: "bio-photo-2.jpg"
  name: "Jimin Lee, M.A."
  pronouns:
  bio: "Research Associate"
  employer: "Institute of Health and Environment,"
  location: "Seoul National University"
  uri:
  email: "jiminlee28@snu.ac.kr"
  academia:
  googlescholar: "https://scholar.google.com/citations?user=zuMXeBkAAAAJ&hl=ko"
  orcid: "https://orcid.org/0009-0005-3284-3373"
